# Generated by Django 5.1 on 2024-08-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feed',
        ),
    ]
