# Generated by Django 5.1 on 2024-08-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app1', '0002_delete_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tile', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media')),
                ('caption', models.CharField(max_length=50)),
            ],
        ),
    ]
